version: '3'
services:
  env:
    build: .
    container_name: 'ds-template'
    working_dir: '/kaggle'
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    volumes:
      - ./:/kaggle
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: jupyter notebook --allow-root --ip=0.0.0.0 --port=8888 --NotebookApp.token='' --notebook-dir=/kaggle
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
